version: "3.9"

services:
  db:
    container_name: db
    image: postgres:14.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=pgdbpwd
      - POSTGRES_USER=go-server
      - POSTGRES_DB=go-musthave-diploma
